name: Build for mbed
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
      name: Build for mbed
      runs-on: ubuntu-latest
      container: mbedos/mbed-os-env:latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install dependencies
          run: |
            cd mbed
            pip install --upgrade mbed-cli mbed-tools
            mbed deploy

        - name: Build
          run: |
            cmake -S mbed -B cmake_build -GNinja -DCMAKE_BUILD_TYPE=Debug
            cmake --build cmake_build
