name: Build for mbed
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
      name: Build for mbed
      runs-on: ubuntu-latest
      container: mbedos/mbed-os-env:latest
      steps:
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Build for mbed
          run: |
            cd mbed
            pip install --upgrade --user mbed-cli mbed-tools
            mbed deploy
            mbed-tools configure -t GCC_ARM -m NRF52840_DK
            cmake -S . -B cmake_build/NRF52840_DK/develop/GCC_ARM -GNinja -DCMAKE_BUILD_TYPE=Debug
            cmake --build cmake_build/NRF52840_DK/develop/GCC_ARM
